language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  # TensorFlow is optional
  - pip install tensorflow
  - pip install -e .
script:
  - python test_deform_grid.py -v
